# Updating and installing packages
- name: Environment for users installing
  hosts: vector
  gather_facts: no
  become: yes
  become_user: root
  tasks:
    - name: Update servers
      command: dnf makecache
    - name: Install packages
      package:
        name:
          - vim
          - tree
          - bash-completion
          - nginx-1:1.18.0-8.el7.3
          - telnet
        state: present
    - name: Check file bash-completion in /home/deploy/.bashrc
      shell: cat /home/deploy/.bashrc | grep -q "Auto-completion"
      ignore_errors: true
      register: grep_result
    - name: Check file bash-completion in /root/.bashrc
      shell: cat /root/.bashrc | grep -q "Auto-completion"
      ignore_errors: true
      register: grep_result
    - name: Read bash-completion file
      slurp:
        src: ../shared_files/bash-completion
      delegate_to: localhost
      become_user: ubuntu
      register: bash_completion_contents
    - name: Adding auto-completion into /home/deploy/.bashrc
      lineinfile:
        path: /home/deploy/.bashrc
        line: "{{ bash_completion_contents['content'] | b64decode }}"
      when: grep_result.rc !=0
    - name: Adding auto-completion into /root/.bashrc
      lineinfile:
        path: /root/.bashrc
        line: "{{ bash_completion_contents['content'] | b64decode }}"
      when: grep_result.rc !=0
    - name: Create user vector
      user:
        name: vector
        password: 123QWErty
        state: present
    - name: Delete password
      command: passwd -d vector

    - name: Create work directory
      file:
        path: /etc/vector
        owner: vector
        group: vector
        state: directory
    - name: Create log directory
      file:
        path: /var/log/vector
        owner: vector
        group: vector
        state: directory
    - name: Create ssl directory
      file:
        path: /etc/vector/ssl
        owner: vector
        group: vector
        state: directory

    - name: Download Vector
      shell: "cd /tmp && wget https://packages.timber.io/vector/0.19.1/vector-0.19.1-x86_64-unknown-linux-gnu.tar.gz"

    - name: Unzip Vector
      unarchive:
        src: /tmp/vector-0.19.1-x86_64-unknown-linux-gnu.tar.gz
        dest: /etc/vector
        remote_src: yes

    - name: Copy binary file and set owner
      shell: |
        cp /etc/vector/vector-x86_64-unknown-linux-gnu/bin/vector /usr/bin/
        chown vector:vector /usr/bin/vector
      args:
        creates: /usr/bin/vector

    - name: Copy variables file and set owner
      shell: |
        cp /etc/vector/vector-x86_64-unknown-linux-gnu/etc/systemd/vector.default /etc/default/
        chown vector:vector /etc/default/vector.default
      args:
        creates: /etc/default/vector.default

    - name: Copy config file
      copy:
        src: "./configs/vector-master.yaml"
        dest: "/etc/vector/vector.yaml"

    - name: Permission
      command: chown -R vector:vector /etc/vector  

    - name: Move configuration files to /etc/vector
      command: sudo su vector -c "mv /etc/vector/vector-x86_64-unknown-linux-gnu/config/* /etc/vector/"

    - name: Remove temp files
      command: rm -rf /etc/vector/vector-x86_64-unknown-linux-gnu /etc/vector/vector.toml

    - name: Daemon reload
      systemd:
        daemon_reload: yes

    - name: Restart the service
      systemd:
        name: vector.service
        state: restarted
