---
- name: Execute tail -f on the remote host
  hosts: all_servers
  gather_facts: no
  become: yes
  become_user: root
  tasks:
    - name: Copy cloud-init.log
      fetch:
        src: /var/log/cloud-init.log
        dest: ./logs_from_vms/{{ inventory_hostname }}-cloud-init.log
        flat: yes

    - name: Copy cloud-init-output.log
      fetch:
        src: /var/log/cloud-init-output.log
        dest: ./logs_from_vms/{{ inventory_hostname }}-cloud-init-output.log
        flat: yes